# Generated by Django 6.0.4 on 2026-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Women', 'Women'), ('Men', 'Men')], max_length=20)),
                ('style_name', models.CharField(max_length=255)),
                ('style_code', models.CharField(blank=True, max_length=100)),
                ('style_id_from_catalog', models.PositiveIntegerField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('fabric', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('color_note', models.CharField(blank=True, max_length=255)),
                ('ref_photo', models.ImageField(blank=True, null=True, upload_to='orders/reference_photos/')),
                ('selected_image_url', models.URLField(blank=True)),
                ('selected_tag', models.CharField(blank=True, max_length=100)),
                ('shoulder', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sleeve', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bust', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dress_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('neck_f', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('waist_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('trouser', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('thigh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('neck_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('urgency', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('urgent', 'Urgent')], default='standard', max_length=20)),
                ('delivery_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Mobile Money (MoMo)', 'Mobile Money (MoMo)'), ('Bank Transfer', 'Bank Transfer'), ('Cash on Delivery', 'Cash on Delivery'), ('Pay on Pick-up', 'Pay on Pick-up')], max_length=50)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='orders/receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
