# Generated by Django 6.0.4 on 2026-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('women', 'Women'), ('men', 'Men')], max_length=20)),
                ('fabric', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('badge', models.CharField(choices=[('New', 'New'), ('Popular', 'Popular'), ('Bestseller', 'Bestseller')], default='New', max_length=30)),
                ('image', models.ImageField(upload_to='styles/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
